### ISSUE TITLE
Crash in 1.20.1 due to Java 17 incompatibility

### ISSUE THREAD

**Issue by Dronicode** [Estecka/mc-Nocturnal-Bats#2]
Hello, 

I've been wanting to try this mod for a while but it always crashes with the following error. I see that I could  switch to OpenJDK 21 but I'm pretty sure this will break compatibility for a lot of the other mods in my modpack. Would it be possible to add compatibility for OpenJDK17 please?

[13:20:12] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED nocturnal-bats 1.1.0+1.21.3 {depends java @ [>=21]}, ROOT_FORCELOAD_SINGLE nocturnal-bats 1.1.0+1.21.3]
[13:20:12] [main/INFO]: Reason: [HARD_DEP nocturnal-bats 1.1.0+1.21.3 {depends java @ [>=21]}]
[13:20:12] [main/INFO]: Fix: add [], remove [], replace [[java 17] -> add:java 21 ([[21,∞)])]
[13:20:12] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
	 - Mod 'Nocturnal Bats' (nocturnal-bats) 1.1.0+1.21.3 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
Process exited with code 1.

**Comment by Estecka** [comment]
For java 17 compatibility, you can use the older version **1.0.0+1.19.4**. It's functionally identical, minus the support for MC 1.21.2.

From experience, Java 17 mods can run on Java 21. The only place where I've seen this being a problem is for people using Forge with Synitra Connector.

**Comment by Dronicode** [comment]
Hi, thank you for the quick response. I may try out Java 21 in the future but installing it on the Steam Deck is a bit of a hassle so your suggestion of using the older version of the mod worked perfect, thank you!
